[build-system]
requires = ["setuptools>=65", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wh-product-manager"
version = "0.1.0"
description = "Shopify product management via GraphQL API"
readme = "README.md"
requires-python = "==3.12.12"
authors = [
    { name = "Wesley Heijnen", email = "wesley-heijnen@hotmail.com"}
]
license = {text = "MIT"}
dependencies = [
    "alembic>=1.18.4",
    "asyncmy>=0.2.11",
    "fastapi>=0.128.2",
    "httpx>=0.28.1",
    "nuitka>=4.0",
    "pydantic>=2.12.5",
    "pydantic-ai>=1.63.0",
    "pydantic-settings>=2.12.0",
    "python-slugify>=8.0.4",
    "sqlalchemy>=2.0.47",
    "uvicorn>=0.40.0",
    "xmltodict>=1.0.2",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
]

[project.urls]
Homepage = "https://github.com/wheijnen174/wh-product-manager"
Repository = "https://github.com/wheijnen174/wh-product-manager.git"

[project.scripts]
wh-dev = "wh_product_manager.run:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
